{% set name = "react-ipywidgets" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/react-ipywidgets-{{ version }}.tar.gz
  sha256: 898497ad579d3b90a032853ef73263c874577b8ffdcd33e63b66ed1f9fca2622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - flit
    - ipywidgets
    - rich
    - typing_extensions
  run:
    - ipywidgets
    - python >=3.6
    - rich
    - typing_extensions

test:
  imports:
    - react_ipywidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/react-ipywidgets/
  summary: Write ipywidgets like React
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
